### ISSUE TITLE
Upload failing with http/413 Request Entity Too Large files over 4MB

### ISSUE THREAD

**Issue by 4n3w** [pivotal-cf/azure-blobstore-resource#3]
Hey there; I'm trying to use the azure-blobstore-resource within a concourse pipeline and when the pipeline uploads files over 4MB I get this error:

```
2018/08/13 21:28:07 failed to upload blob: storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.
RequestId:50459769-801e-0017-184c-33f80a000000
Time:2018-08-13T21:28:06.9913482Z, RequestInitiated=Mon, 13 Aug 2018 21:28:06 GMT, RequestId=50459769-801e-0017-184c-33f80a000000, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=
```

Confirmed that I'm able to upload smaller files that are smaller than 4MB. It looks like there's some chunking that needs to happen to allow for files larger than 4MB.

**Comment by christianang** [comment]
Hi @4n3w,

I finally had a moment to implement this. I've tested it with a 400mb file and it works, but try it out and let me know if you have any issues.

FYI, the resource now lives under `pcfabr/azure-blobstore-resource` instead of `czero/azure-blobstore-resource` so to get the fix you will need to switch to the new resource repo.

**Comment by christianang** [comment]
Closing. Feel free to reopen if you run into issues.
