### ISSUE TITLE
0.6.x fails any resource that requires unpack: true

### ISSUE THREAD

**Issue by svrc-pivotal** [pivotal-cf/azure-blobstore-resource#32]
Was using this with tag "latest" at a customer and all pipelines started failing because they use this resource with `unpack: true` for Platform Automation image and tasks.   

Reverted to 0.5.0 and it works again.

**Comment by christianang** [comment]
Good find. This should be fixed in https://github.com/pivotal-cf/azure-blobstore-resource/releases/tag/v0.7.0. It now relies on a golang library instead of shelling out to the tar/unzip/gzip programs. I tested this with a few different packages, but feel free to reopen the issue if there are problems.
